### ISSUE TITLE
Update Workflow(s) for CLI Builds

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/OctopusCLI#180]
File: build.yml

**Tasks**

- [x] Utilise [GitVersion (GitHub Actions)](https://github.com/marketplace/actions/gittools)
- [x] Support nightlies (i.e. `-nightly`) via GitHub Actions (cron)
- [x] Release notes generated through [Release-Please](https://github.com/googleapis/release-please)
- [x] Slack notifications to internal teams (@jbristowe)
- [x] CHANGELOG.md auto-generation
